version: '3.1'

services:
  django:
    container_name: cbp
    image: cbp:0.7
    environment:
      DJANGO_SUPERUSER_NAME: root
      DJANGO_SUPERUSER_EMAIL: root@example.ru
      DJANGO_SUPERUSER_PASSWORD: password
    command: /bin/bash ./run.sh
    ports:
      - "8000:8000"
      - "20-21:20-21"
      - "65500-65515:65500-65515"
    depends_on:
      - db
    volumes:
      - ./cbp/logs:/logs
      - ./data/backup:/backups
      - ./data/diffs:/diffs
      - ./data:/data
      - ./cbp.conf:/home/django/cbp.conf

  db:
    container_name: cbp-mysql-server
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'cbpsij!*!43'
      MYSQL_DATABASE: 'cbp'
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
