version: '3.1'

services:
  cbp:
    container_name: cbp
    image: cbp:0.7
    hostname: cbp_host
    environment:
      DJANGO_SUPERUSER_NAME: root
      DJANGO_SUPERUSER_EMAIL: root@example.ru
      DJANGO_SUPERUSER_PASSWORD: password
      LOCAL_HOST_BACKUP_IP: '10.0.0.47'
      LOCAL_HOST_IPS: '10.0.0.47, 127.0.0.1'
      LOCAL_FTP_USER_NAME: ftpuser
      LOCAL_FTP_USER_PASS: pass
      LOCAL_FTP_USER_HOME: /home/ftpuser
    command: /bin/bash ./run.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./ftp:/home/ftpuser
      - ./cbp:/home/django/cbp
      - ./backup.py:/home/django/backup.py
      - ./cbp.conf:/home/django/cbp.conf
      - ./templates:/home/django/templates
      - ./CbP_web:/home/django/CbP_web

  db:
    container_name: cbp-mysql-server
    hostname: cbp_mysql_bd
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'cbpsij!*!43'
      MYSQL_DATABASE: 'cbp'
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql

  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: cbp-ftpd
    hostname: cbp_ftpd_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./ftp:/home/ftpuser"
    environment:
      PUBLICHOST: "10.0.0.47"
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: pass
      FTP_USER_HOME: /home/ftpuser
      FTP_MAX_CLIENTS: 15
    restart: always
